// Generated by Supabase MCP - Phase 3 Database Types
// Date: 2026-01-30
// Project: Orion AI - The Secure Context (Data & RAG)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      document_chunks: {
        Row: {
          chunk_index: number
          chunk_text: string
          created_at: string | null
          document_id: string
          embedding: string
          id: string
          metadata: Json | null
          token_count: number | null
        }
        Insert: {
          chunk_index: number
          chunk_text: string
          created_at?: string | null
          document_id: string
          embedding: string
          id?: string
          metadata?: Json | null
          token_count?: number | null
        }
        Update: {
          chunk_index?: number
          chunk_text?: string
          created_at?: string | null
          document_id?: string
          embedding?: string
          id?: string
          metadata?: Json | null
          token_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "document_chunks_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      document_permissions: {
        Row: {
          document_id: string
          granted_at: string | null
          granted_by: string
          id: string
          permission: string
          team_id: string | null
          user_id: string | null
        }
        Insert: {
          document_id: string
          granted_at?: string | null
          granted_by: string
          id?: string
          permission?: string
          team_id?: string | null
          user_id?: string | null
        }
        Update: {
          document_id?: string
          granted_at?: string | null
          granted_by?: string
          id?: string
          permission?: string
          team_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "document_permissions_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "document_permissions_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          content: string
          created_at: string | null
          created_by: string
          document_type: string
          file_path: string | null
          id: string
          metadata: Json | null
          source_url: string | null
          team_id: string | null
          title: string
          updated_at: string | null
          visibility: string
        }
        Insert: {
          content: string
          created_at?: string | null
          created_by: string
          document_type?: string
          file_path?: string | null
          id?: string
          metadata?: Json | null
          source_url?: string | null
          team_id?: string | null
          title: string
          updated_at?: string | null
          visibility?: string
        }
        Update: {
          content?: string
          created_at?: string | null
          created_by?: string
          document_type?: string
          file_path?: string | null
          id?: string
          metadata?: Json | null
          source_url?: string | null
          team_id?: string | null
          title?: string
          updated_at?: string | null
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      embedding_cache: {
        Row: {
          created_at: string | null
          dimensions: number
          embedding: string
          last_used_at: string | null
          model: string
          text_hash: string
          use_count: number | null
        }
        Insert: {
          created_at?: string | null
          dimensions?: number
          embedding: string
          last_used_at?: string | null
          model?: string
          text_hash: string
          use_count?: number | null
        }
        Update: {
          created_at?: string | null
          dimensions?: number
          embedding?: string
          last_used_at?: string | null
          model?: string
          text_hash?: string
          use_count?: number | null
        }
        Relationships: []
      }
      process_events: {
        Row: {
          activity_id: string | null
          duration_ms: number | null
          error_data: Json | null
          event_name: string
          event_timestamp: string | null
          event_type: string
          id: string
          input_data: Json | null
          metadata: Json | null
          output_data: Json | null
          status: string
          user_id: string | null
          workflow_id: string | null
          workflow_run_id: string | null
        }
        Insert: {
          activity_id?: string | null
          duration_ms?: number | null
          error_data?: Json | null
          event_name: string
          event_timestamp?: string | null
          event_type: string
          id?: string
          input_data?: Json | null
          metadata?: Json | null
          output_data?: Json | null
          status: string
          user_id?: string | null
          workflow_id?: string | null
          workflow_run_id?: string | null
        }
        Update: {
          activity_id?: string | null
          duration_ms?: number | null
          error_data?: Json | null
          event_name?: string
          event_timestamp?: string | null
          event_type?: string
          id?: string
          input_data?: Json | null
          metadata?: Json | null
          output_data?: Json | null
          status?: string
          user_id?: string | null
          workflow_id?: string | null
          workflow_run_id?: string | null
        }
        Relationships: []
      }
      team_members: {
        Row: {
          joined_at: string | null
          role: string
          team_id: string
          user_id: string
        }
        Insert: {
          joined_at?: string | null
          role?: string
          team_id: string
          user_id: string
        }
        Update: {
          joined_at?: string | null
          role?: string
          team_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_members_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          org_id: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          org_id?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          org_id?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_document_with_chunks: {
        Args: { doc_id: string }
        Returns: {
          chunk_count: number
          content: string
          created_at: string
          document_type: string
          id: string
          title: string
          visibility: string
        }[]
      }
      match_documents: {
        Args: {
          match_count?: number
          match_threshold?: number
          query_embedding: string
        }
        Returns: {
          chunk_index: number
          chunk_text: string
          document_id: string
          document_title: string
          id: string
          similarity: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types for easy access
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Convenience type aliases for Phase 3 tables
export type Document = Tables<'documents'>
export type DocumentChunk = Tables<'document_chunks'>
export type Team = Tables<'teams'>
export type TeamMember = Tables<'team_members'>
export type DocumentPermission = Tables<'document_permissions'>
export type ProcessEvent = Tables<'process_events'>
export type EmbeddingCache = Tables<'embedding_cache'>

// Function return types
export type MatchDocumentsResult = Database['public']['Functions']['match_documents']['Returns'][number]
export type DocumentWithChunks = Database['public']['Functions']['get_document_with_chunks']['Returns'][number]
